version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: finance
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432

  web:
    build: .
    ports:
      - "9000:9000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
    volumes:
      - .:/app
    depends_on:
      - db