version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurants
      POSTGRES_PASSWORD: restaurants12-
    ports:
      - 5433:5432

  web:
    build: .
    environment:
      - ENVIRONMENT=development
      - POSTGRESQL_URL=postgresql://postgres:restaurants12-@db:5432/restaurants
    ports:
      - "9000:9000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"]
    volumes:
      - .:/app
    depends_on:
      - db